// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateDocumentInput struct {
	Value        string `json:"value"`
	AccessKey    string `json:"accessKey"`
	MaxViewCount *int   `json:"maxViewCount,omitempty"`
	TTLMs        *int   `json:"ttlMs,omitempty"`
}

type Document struct {
	ID           int       `json:"id"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	Value        string    `json:"value"`
	AccessKey    string    `json:"accessKey"`
	ViewCount    int       `json:"viewCount"`
	MaxViewCount int       `json:"maxViewCount"`
	TTLMs        int       `json:"ttlMs"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateDocumentInput struct {
	ID           int     `json:"id"`
	Value        *string `json:"value,omitempty"`
	AccessKey    string  `json:"accessKey"`
	MaxViewCount int     `json:"maxViewCount"`
	TTLMs        int     `json:"ttlMs"`
}
